name: Update scrapers dependencies

on:
  push:
    branches:
      - main

jobs:
  sync_reqs:
    if: github.ref == 'refs/heads/main'
    name: Sync poetry lock with new cyclades-openstates-core version
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Get GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: "washabstract"

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: "washabstract/cyclades-openstates-scrapers"
          token: ${{ steps.app-token.outputs.token }}
          ref: main

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh

      - name: install poetry
        run: pip install poetry==1.8.4

      - name: update poetry lock
        run: poetry lock

      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet poetry.lock; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Configure git
        run: |
          git config --global user.name "send-pr.yml workflow"
          git config --global user.email "<>"

      - name: Checkout new branch
        run: git checkout -b update-core-dependency-${GITHUB_SHA}

      - name: Commit the changes
        run: git commit poetry.lock -m "Update Poetry.lock to ${GITHUB_SHA}"

      - name: Push branch
        run: git push --force origin update-core-dependency-${GITHUB_SHA}:update-core-dependency-${GITHUB_SHA}

      - name: Authenticate gh CLI
        run: echo "${{ steps.app-token.outputs.token }}" | gh auth login --with-token

      - name: Create PR
        run: |
          gh pr create \
          --base main \
          --head update-core-dependency-${GITHUB_SHA} \
          --body "Auto-update dependencies from cyclades-openstates-core commit ${GITHUB_SHA}" \
          --title "Update core dependencies (${GITHUB_SHA:0:7})"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}